### ISSUE TITLE
bug: a image cannot be displayed correctly

### ISSUE THREAD

**Issue by dqhl76** [UlanqabBadGuy/LearningNote#1]
https://github.com/UlanqabBadGuy/LearningNote/blob/master/On%20the%20Automatic%20Generation%20of%20Medical%20Imaging%20Reports.md
<img width="1273" alt="image" src="https://github.com/UlanqabBadGuy/LearningNote/assets/69136320/d6d8b9f4-d7bc-40df-9843-c21f4e57fab3">

**Comment by UlanqabBadGuy** [comment]
Hi, thanks for your correction and I fixed it.

**Comment by dqhl76** [comment]
Cool ~
